os:
- linux
- osx
sudo: required
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libpcap0.8
    - libpcap0.8-dev
notifications:
  email: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="12"
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && source
  ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- node --version
- npm --version
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-5; export CC=gcc-5; fi
- "$CXX --version"
- npm install
script: sudo $(type -P node) test/test.js
deploy:
  provider: npm
  email: roman.balzer@gmail.com
  api_key:
    secure: AJxX9Df1WAJMPtJA2VMHvPbXu2rnejk7Oj93YhYiD7txa0ryZxW90Qbb+FVWCJvxdjWF5Tow5PY94O+QDDmwCV290QLX6kgE3kcYV1KJNiQ1kcSS2EkHoFkiwlmzc/qoiW/+aaVUkva/7rqmIKcSzQ9JV7RWIApkkptdQWCbgjcY599i+Iv0Ni8oRoVdwUkpOSSsLWbVFCE75PnX2HVoAIuhBtfhOJ1v1n1+bLfeXIM8QBRbyX+d3WdwqKCyU3rFC15Y+zf2M96/jCcpkhtwGUVyWL3ttci4OtEqnRch3oJfKPNDAqwrNobMm1bjLc3ufLFahJmpxl03queT1DrmyzmyTw8RM1+kvBv03aRc0kkju38pep5pmSyUG/uZJG7bMV1GNftpi5jEX74Hy5U3FCnEszblMum0H9OJ3gM5hFld9BtMPajmCOiQ7no1OzTX98tXz4XN8Mfkb9dmRs+uDTk38XsnZx6yXGkxUuA10VnbFwFzYaq1cXbWUiO1as/SkGWe516kVUcYoSFRToTPStpX6nOs5HZN3XIJruzp+Mdz5BoAmYmAKZvOP4BETXOKOqOviQNOnv7HKXLCREnDeb3hi3gplwG29Bqh5CrEpwDx9Tm+GrRhPOzscyIXDUtZE70icL4UAPWVgN/U/Cosagre+gGAQ1lKRD+GmnyvOBY=
  on:
    repo: roman-balzer/cap
  skip_cleanup: 'true'
