os:
- linux
- osx
sudo: required
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libpcap0.8
    - libpcap0.8-dev
notifications:
  email: false
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="12"
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && source
  ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- node --version
- npm --version
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-5; export CC=gcc-5; fi
- "$CXX --version"
- npm install
script: sudo $(type -P node) test/test.js
deploy:
  provider: npm
  email: roman.balzer@gmail.com
  skip_cleanup: true
  api_key:
    secure: HepqDkGR3cYvHutoELakM+oDO1tzK95l2L+KcOg8lLa20WADFeG6m++HhYPij/lPkOgt026uHyxpjyj8S1WSwGUp99CePF0jQsoukNsv81PPE7f2TIsZxwcHMt9pgqlFdIJcxYlTVsgqCcR3ScZexO83mHO0DxKJQ3HhwrQev5vVC+BjWWMV1zxAc/mL+BbCz/lWG355kB8WVGQv88UhpuGfbPIPN0A12m8c2AvU0ti16Eniip06+7NQgNBcpNZ3RpIt7WSOfnvEpeQfESNF1mmjIpbmrzvEpIp6e1Eqh+kCxhR2qB7danerrt+h/xjYXICG4YswIq0Ketr1PrH/U/0TCHuOu+XXvAiK8VmBpoo3vic3gR3hCIWoXg8O9oLlFs1sjM2sV1qITdHaC18OfYYdGVNlAXcH1djDyARB8lOaqPkYj0qD5l45xIPBoiIEygOfrv0ewKW2ki0alTTGexET0pnLoIsktwzHFwUqxx+SxnuYFJWsZrpmZL+b2Aq/aufHvvelQCQ4h1Jxsi6bYrh/OAvsEezRJ82m2rbW26YaHLQd3D7HbOYrzmdMN9xeebNWa7rfevPG/h3pmyK3aFmsWheUC1PtOU7rd55xQrC/smTpFXmWWTxdHcG/TxkayBCdin/HV+vZFSGvmJjZM0jA8e1pOERnRddqVUMV0VE=
  on:
    branch: master
